project:
  type: book
  output-dir: docs

book:
  title: "Project Implementation and Management Guideline"
  author: "Frontieri"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - phase.qmd
    - feature.qmd
    - problem.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



